### ISSUE TITLE
How do I run it for a single image or list of images?

### ISSUE THREAD

**Issue by Witek-** [jchenghu/ExpansionNet_v2#1]
Hi,

How do I run the code (preferably in Colab) to generate captions for a single image or for a few images? No further evaluation is neccessary.

Thanx

**Comment by jchenghu** [comment]
Hi, 

I’m guessing you want a small script (requiring only the trained weights) that test the model without over-complicated training setups, data or computational requirements. I haven't pushed yet a little script for generic images (not included in COCO), in case you are interested, let me know. 

In case you only wanted to see more results on COCO images you can check `test_karpathy_5000.txt` we just uploaded in the [drive](https://drive.google.com/drive/u/5/folders/1bBMH4-Fw1LcQZmSzkMCqpEl0piIP88Y3) (plain text file, no json, so it can be straightforwardly visualized) .

Regarding Colab, you can try (assuming a blank project):
```
!git clone https://github.com/jchenghu/ExpansionNet_v2
cd ExpansionNet_v2
```

and then execute the commands provided by the README such as
```
!python data_generator.py \
--save_path ./github_ignore_material/raw_data/swin_large_patch4_window12_384_22k.pth \
--output_path ./github_ignore_material/raw_data/features.hdf5 \
--image_path ./github_ignore_material/raw_data/MS_COCO_2014/ \
--captions_path ./github_ignore_material/raw_data/
```

(note that ‘python’ is preceded by an exclamation point) assuming that all required files are already in place.

Let me know If I answered your question :-)

**Comment by Witek-** [comment]
Hi, 
Thank you for your quick answer. I will try the method you suggsted, but a small script requiring only the trained weights and working on generic images would be great.

**Comment by jchenghu** [comment]
Hi,

I pushed the script called `demo.py`, you can find the instructions at the end of the README, let me know
if everything is fine :-)

In case you're running Colab, the procedure reported in my previous answer should do the job (replacing `!python train.py ...` with `!python demo.py ...`) . Instead, if you encounter problems related to Colab in the training procedure later on (given the amount of data it may take understandably some time) I would suggest you to open another issue and report the problems related to that specific environment so it may be easier to find for other users.

Best regards, Jia

**Comment by Witek-** [comment]
Thanks a lot. This is exactly what I had in mind.
