### ISSUE TITLE
online testing CUDA overflow

### ISSUE THREAD

**Issue by PanYuQi66666666** [jchenghu/ExpansionNet_v2#21]
Hello, I use the Ensemble model to do online testing. I use a single A100-40G to display my CUDA overflow. Is there any good way to solve this problem? What should I do if I increase the number of A100-40Gs to two?

**Comment by jchenghu** [comment]
Hi, so you get CUDA Memory overflow in the case of a single GPU, I think the simplest solution would be reducing the --eval_parallel_batch_size which defaults to 16. You may want to lower this value:

Something like 
```
python test.py --N_enc 3 --N_dec 3 --model_dim 512 \
    ...
    --eval_parallel_batch_size 4 \
    ...
``` 

Or even lower if needed
Let me know if it helps or you have already tried this solution

**Comment by jchenghu** [comment]
Hi, I'm closing the issue, I assume the it was solved based on the other thread
