### ISSUE TITLE
Hi, I actually have a question, why is the swin transformer fine-tuned during training, but the parameters of the final model remove the parameters of the swin-transformer?

### ISSUE THREAD

**Issue by PanYuQi66666666** [jchenghu/ExpansionNet_v2#22]
Hi, I actually have a question, why is the swin transformer fine-tuned during training, but the parameters of the final model remove the parameters of the swin-transformer?

**Comment by jchenghu** [comment]
Hi, which training stage are you referring to? The swin-transformer parameters are not typically removed in the final model. 

If you're wondering why it is removed in the partial training steps, it is done to achieve faster training. We can afford to do so because we regenerate the visual features with the updated swin-transformer right before the partial step

**Comment by PanYuQi66666666** [comment]
No, the weight model I got after reproducing it has a parameter of 233803076, which is different from the paper. I asked you before and you said to remove model.swin_transf. I don’t quite understand this because in the process of reproducing it, in the Cross Entropy– End to End. and CIDEr-D optimization– End to End. stages, didn’t you release the parameters of the swin transformer to learn? @jchenghu

**Comment by jchenghu** [comment]
> No, the weight model I got after reproducing it has a parameter of 233803076, which is different from the paper. 

Hi, in this [paper](https://arxiv.org/pdf/2208.06551), we compared the number of parameters without the backbone.
In case you add the backbone, which is 197M, once you add the fusion model you reach around the value you reported
so if you are in the end-to-end training, your value seems about right.

> I asked you before and you said to remove model.swin_transf. 

Can you share the link of the thread where I've said this? It could have been a misunderstanding

The swin_transf parameters are removed only during the partial training (training steps 2 and 5 in the Readme).
Note that, in step 3 you train also swin-transformer weights, you generate its features in step 4, then you load the weights of step 3 back in step 5, so we are not removing or discarding them.

**Comment by PanYuQi66666666** [comment]
OK, I am a newbie in the field of image captioning. I would like to ask if the standard for comparing model parameters in this field does not include fine-tuning the image encoder parameters? You gave me this code to test the number of model parameters: def count_parameters(model):
return sum(p.numel() for p in model.parameters() if p.requires_grad)
print("The model w/o backbone has " + str(count_parameters(model) - count_parameters(model.swin_transf)) + " parameters"). If I do related work in the future, will I also compare in this way?

**Comment by jchenghu** [comment]
Glad the doubts were clarified!

Currently, I don't think there is a standard for reporting the number of parameters. It depends on the context, for instance, if you are focusing on the fusion model I think excluding the backbone parameters is reasonable. Instead, if you are also changing the backbone, it can be a good idea to report that as well.

The best solution would be reporting both measures but it can create confusion for the reader in some cases, and it was one of the reasons why we decided not to in our paper, in addition to the space limitation.

**Comment by PanYuQi66666666** [comment]
OK, I saw the model parameter comparison you reported in the paper. For example, pureT, the model parameters reported in his paper also do not include the visual encoder?

**Comment by jchenghu** [comment]
Yes the number of parameters reported for PureT in our paper, does not include the visual encoder. 

In general, however, not only there isn't a standard, but I think it is rare to find the number of parameters in other papers sadly, so it is really up to your preferences.

**Comment by PanYuQi66666666** [comment]
OK
