### ISSUE TITLE
how long it takes to run test.py on a 3060 

### ISSUE THREAD

**Issue by qqq-gif** [jchenghu/ExpansionNet_v2#23]
I would like to know approximately how long it takes to run test.py on a 3060 video card using the rf_model_140 file you provided, I would like to see if I can run out of 140, my terminal has been in this state for two or three hours now, is this normal please?
![图片1](https://github.com/user-attachments/assets/03be4ffb-d794-45fc-81d3-77e198fad128)
![图片2](https://github.com/user-attachments/assets/50174c13-0cde-4c3c-bace-c00a34146bbc)

**Comment by jchenghu** [comment]
Hi, 

It is not normal, it shouldn't take that much, I expect it to be around 10 minutes on a 3060,
although it might be more due to the smaller size of the evaluation batch

Can you try adding some print here? 
In the "evaluate_model" function:
```
for sb_it in range(num_iter_sub_batches):
    last_iter = sb_it == num_iter_sub_batches - 1
    if last_iter:
        from_idx = sb_it * sb_size
        to_idx = num_samples
    else:
        from_idx = sb_it * sb_size
        to_idx = (sb_it + 1) * sb_size
        
    print("sb_it: " + str(sb_it) + " elapsed: " + str(time()-start_time) + " seconds")
    ^^^^^ something like this
```
and then launch the test again, to see if the program is actually running or stuck somewhere

**Comment by qqq-gif** [comment]
Thank you, I added the print message and re-ran it twice and found that it was stuck at the 1248th hour.
![Uploading 图片3.png…]()

**Comment by qqq-gif** [comment]
![图片3](https://github.com/user-attachments/assets/ddd45002-b4e8-4dbf-9b3a-7b0cd07beeee)

**Comment by jchenghu** [comment]
Ok, we at least know it works fine on the 3060

Now, being stuck at sb_it: 1248 is quite weird, either it was extremely unlucky, and got stuck at the final iteration ( 5000 samples, given a batch size of 4, it should reach 1249 before exiting ) or it is a visual bug

Try adding this 

```
            del sub_batch_x, sub_batch_x_num_pads, output_words

    ddp_model.train()
    
    print("Time to call evaluation metrics") 
    ^^^ this line
    
    if rank == 0 and verbose:
        # dirty code to leave the evaluation code untouched
        list_predictions = [sub_predictions for sub_predictions in sub_list_predictions]
        list_list_references = [[validate_y[i][j] for j in range(len(validate_y[i]))] for i in range(len(validate_y))]
 ```
 and let's see if it shows sb_it:1249 now

**Comment by qqq-gif** [comment]
Thanks, I added the print message you mentioned and reported missing java, but I have installed and configured the java environment, as shown in the picture I executed java -verison
![图片5](https://github.com/user-attachments/assets/373d34a0-4496-4e16-a8ba-4b0ec52359bd)

**Comment by jchenghu** [comment]
Mmh... can you show me the result again, after these two operations:
- delete all .json files in the eval/spice/tmp directory 
- delete all files in eval/spice/cache directory

**Comment by qqq-gif** [comment]
The problem seems to be that I can't execute the contents of the file D:\TQQ\ExpansionNet_v2-master\eval\get_stanford_models.sh under Win system. stanford_models.sh file into a valid executable for win system.
![图片6](https://github.com/user-attachments/assets/5cb59846-79c5-4be6-b931-af360f7fba45)

**Comment by jchenghu** [comment]
good job, we might be getting closer to the solution

the "get_stanford_models.sh" is a bash script after all, maybe you can try doing manually the operations inside it

So download `http://nlp.stanford.edu/software/stanford-corenlp-full-2015-12-09.zip`
extract it and put `stanford-corenlp-3.6.0.jar` and `stanford-corenlp-3.6.0-models.jar` into `/spice/lib/`

**Comment by qqq-gif** [comment]
Thanks for your reply, I downloaded those two files manually, and deleted the files under cache and tmp, and commented out the lines about get_stanford_models_path in eval.py and test.py, and then ran test.py again, now it doesn't report an error, but still doesn't come up with a score why? And I found that the file D:\TQQ\ExpansionNet_v2-master\eval\spice\cache\data.mdb is actually 97.66GB!
![图片7](https://github.com/user-attachments/assets/454a5235-e4c6-4001-87f4-e4abaf57362c)

**Comment by qqq-gif** [comment]
I think the problem must be somewhere in the assessment, because when I was doing the training, the stage assessment was also unable to show the score
![图片8](https://github.com/user-attachments/assets/150cee1d-9813-418e-8d9f-ea4406da6e4b)

**Comment by jchenghu** [comment]
Wow, 100GB in the cache is absurd. 

Could you show the score without the spice? 
For instance, go to 'eval/eval.py' and comment away these lines
```

        if rouge:
            scorers.append((Rouge(), "ROUGE_L"))
        #if spice:
        #    scorers.append((Spice(), "SPICE"))
        # comment these two lines away
        if meteor:
            scorers.append((Meteor(), "METEOR"))

```
Let's ensure everything else works fine

**Comment by qqq-gif** [comment]
I've tried the method you mentioned, no matter how I change it, the score is never printed, I've changed the nccl in test.py to gloo before, may I ask if it has anything to do with this

**Comment by jchenghu** [comment]
Hi, you should not change NCCL to GLOO since as stated [here](https://pytorch.org/docs/stable/distributed.html), GLOO is for CPU-distributed processing, instead, we want to run on GPU. That could be the issue indeed.

If reverting to NCCL does not solve your issue, and evaluation is stuck even when SPICE is commented out, I would suggest you print the sentences here, to check if the descriptions are correctly generated

in `evaluate_model` function inside `test.py`
```
         score_results = coco_eval.evaluate(bleu=True, rouge=True, cider=True,
                                           spice=False,  # you can set spice to false if you didn't comment it inside eval.py
                                           meteor=True, verbose=False)
        elapsed_ticks = time() - start_time

        print("Examples:")
        for z in range(10):
            print("pred: " + str(list_predictions[z]), end=" ")
            print("refs: " + str(list_list_references[z]))
```
I expected that by excluding the SPICE evaluation the running would at least show the other metrics, but since it did not, let's see at least if the descriptions are all alright

**Comment by qqq-gif** [comment]
Dear Sir, Hello, I am reproducing your code, this is the first step of cross-entropy training after extracting the image features, that is, the result obtained from your (2. Cross-Entropy Training: Partial Training) step, is it correct please?
![图片9](https://github.com/user-attachments/assets/b74ae9c3-4df7-4c5b-ba8b-7fe153336f75)

**Comment by jchenghu** [comment]
good! Yes, the result looks fine

**Comment by qqq-gif** [comment]
I can't use nccl because I'm on win and I only have a GPU3060, is there any replacement for nccl?
![图片10](https://github.com/user-attachments/assets/515bf259-3d82-4ad7-abe5-469437053954)

**Comment by jchenghu** [comment]
Unfortunately, I don't know of workarounds for Windows 
https://github.com/pytorch/pytorch/issues/89688
I suggest you install a Linux distribution which most repositories are built around
