### ISSUE TITLE
Zero scores during evaluation

### ISSUE THREAD

**Issue by jchenghu** [jchenghu/ExpansionNet_v2#6]
Hi, @jchenghu
I'm sorry, but I'd like to ask you a question, too. 
I am also trying to train with custom data, so as you told me above, I modified train.py.
and also, test.py seems to need to be revised, so I revised the same part.
However, there is a problem in the process of validation.

In cider_scorer.py, the value of self.document_frequency is empty. 
Therefore, line 190 of cider_scorer.py got failed. 
so, I just set the default to zero and run the code, then all metric values got zero.
![image](https://github.com/jchenghu/ExpansionNet_v2/assets/59046007/0c4620de-5d7a-4772-9e39-4360184fb6d1)
I think eval.py has some problem. (because all metric got zero)

Is it okay to just run it as it is? (I mean just skip the validation part)
Also, if not, which part of it would need to fix?
Thank you so much

_Originally posted by @hoe-y in https://github.com/jchenghu/ExpansionNet_v2/issues/5#issuecomment-1694453294_

**Comment by jchenghu** [comment]
Hi @hoe-y I created a new issue here so I can better focus on your issue. 

First of all, thank you for the detailed report. 

Regarding the zeros, if you used the training commands presented in the README, this could be a normal situation, due to the fact that in the first 10,000 iterations, a very small learning rate is adopted (for warmup). Before the 10.000 iterations metrics are expected to be around zero because not much is learned in these steps (as I can see from the validation loss). The dataset seems to be made 1456 batches, maybe lowering the warmup steps from 10,000 to 200 (for example) could yield some noticeable results in the very first epoch.

About the empty document_frequency dictionary, this is indeed pretty odd. It should contain the n-grams such as 
`{('a', 'boy', 'holding', 'an'): 2.0, ('to','a','herd'): 3.0,...`
whereas 'gts' and 'res' in the function 
    def compute_score(self, gts, res):
 should be structured as:
```
 gts:
 {0: ['a child holding a flowered umbrella and petting a yak', 'a young man holding an umbrella next to a herd of cattle', 'a young boy barefoot holding an umbrella touching the horn of a cow', 'a young boy with an umbrella who is touching the horn of a cow', 'a boy holding an umbrella while standing next to livestock'],
1:['a narrow kitchen filled with appliances and cooking utensils', 'a galley kitchen with cabinets and appliances on both sides', 'a hallway leading into a white kitchen with appliances', 'doorway view of a kitchen with a sink stove refrigerator and pantry', 'the pantry door of the small kitchen is closed'], ...}

res:
{0: ['a man standing next to a herd of cows'],
 1: ['a kitchen with a white door and a white door'], ... }
 ```
I'd suggest checking the arguments of the evaluation function... That being said, I'll replicate the toy example I made in the other issue and try to replicate the issue myself, so I'll keep you updated. For the time being, thank you very much for reporting the issue and I hope the answer helped a little.

Best regards,
Jia

**Comment by myyzzzoooo** [comment]
Thank you very much for your quick reply!!
and also let me check if I made some mistake..

**Comment by jchenghu** [comment]
Hi, in the picture, the data loader reported correctly 13/14 or 15 mean target length, so
the custom dataset creation in the dataset and dataloader should be fine....

So the problem could be somewhere in test.py ... the custom data set creation reported in https://github.com/jchenghu/ExpansionNet_v2/issues/5 shouldn't require you to change the test.py file... can you show me the changes?

Additionally, if possible, can you also show me one element of the custom data json or even just one sample of self.train_list? (in case of sensible data, you can mask the actual content, I'm just interested in how it is structured)

**Comment by myyzzzoooo** [comment]
Hi!
This is my data structure.
![image](https://github.com/jchenghu/ExpansionNet_v2/assets/59046007/0760958e-f175-4e53-962d-d22c33d2a489)

and i edit this part of test.py. the Dataset and loader. I don't change the COCOEvalCap.
![image](https://github.com/jchenghu/ExpansionNet_v2/assets/59046007/bccd0547-591e-4cfb-8d7d-bbee18df2584)
![image](https://github.com/jchenghu/ExpansionNet_v2/assets/59046007/6cd9cb85-96d0-4594-90ea-2199944b9556)
(I set the image path to blacnk because i put the exact path in my json file)


I'm very grateful to you for all your help.
Thank you

**Comment by jchenghu** [comment]
Hi, your welcome :-)

Your json and code are fine, however, I couldn't replicate the problem of empty document_frequency, I uploaded the changes I made to the code according to issue_5 in this drive https://drive.google.com/drive/folders/11cSkRqRynxfljbOyY9XoFlvOtfXWIpjn?usp=sharing. I didn't change the test.py file because the changes you reported are required only in case we execute directly test.py instead of train.py ... 

here's my output:
<details>
  <summary>My output</summary>

  seed: 775533
train batch_size: 2
num_accum: 1
ddp_sync_port: 11317
save_path: ./github_ignore_material/saves/
num_gpus: 1
Features path: /<MY_DATA_PATH>/features.hdf5
Features path provided, images are provided in form of features.
{'img_path': './github_ignore_material/raw_data/train/1_train_blue.jpg', 'img_id': 1, 'captions': ['a pair of blue socks']}
{'img_path': './github_ignore_material/raw_data/train/2_train_blue.jpeg', 'img_id': 2, 'captions': ['a pair of blue socks']}
{'img_path': './github_ignore_material/raw_data/train/3_train_blue.jpg', 'img_id': 3, 'captions': ['a pair of blue socks']}
{'img_path': './github_ignore_material/raw_data/train/4_train_blue.jpg', 'img_id': 4, 'captions': ['a pair of blue socks']}
{'img_path': './github_ignore_material/raw_data/train/5_train_red.jpeg', 'img_id': 5, 'captions': ['a pair of red socks']}
{'img_path': './github_ignore_material/raw_data/train/6_train_red.jpg', 'img_id': 6, 'captions': ['a pair of red socks']}
{'img_path': './github_ignore_material/raw_data/train/7_train_red.jpg', 'img_id': 7, 'captions': ['a pair of red socks']}
{'img_path': './github_ignore_material/raw_data/train/8_train_red.jpeg', 'img_id': 8, 'captions': ['a pair of red socks']}
{'img_path': './github_ignore_material/raw_data/train/9_train_green.jpg', 'img_id': 9, 'captions': ['a pair of green socks']}
{'img_path': './github_ignore_material/raw_data/train/10_train_green.jpeg', 'img_id': 10, 'captions': ['a pair of green socks']}
{'img_path': './github_ignore_material/raw_data/train/11_train_green.jpg', 'img_id': 11, 'captions': ['a pair of green socks']}
{'img_path': './github_ignore_material/raw_data/train/12_train_green.jpg', 'img_id': 12, 'captions': ['a pair of green socks']}
{'img_path': './github_ignore_material/raw_data/test/1_test_green.jpeg', 'img_id': 13, 'captions': ['a pair of green socks']}
{'img_path': './github_ignore_material/raw_data/test/2_test_blue.jpg', 'img_id': 14, 'captions': ['a pair of blue socks']}
{'img_path': './github_ignore_material/raw_data/test/3_test_red.jpg', 'img_id': 15, 'captions': ['a pair of red socks']}
{'img_path': './github_ignore_material/raw_data/val/1_val_green.jpg', 'img_id': 16, 'captions': ['a pair of green socks']}
{'img_path': './github_ignore_material/raw_data/val/2_val_blue.jpeg', 'img_id': 17, 'captions': ['a pair of blue socks']}
{'img_path': './github_ignore_material/raw_data/val/3_val_red.jpg', 'img_id': 18, 'captions': ['a pair of red socks']}
Num train images: 12
Num val images: 3
Num test images: 3
tot tokens 9 less than 1: 0 remaining: 9
There are 11 vocabs in dict
Max sequence length: 27
y vocabulary size: 11
Using -  1  processes / GPUs!
Requested num GPUs: 1
GPU: 0] Process 0 working...
Cross Entropy learning mode
0] data.custom_dataloader) Dataset epoch initialization 0.0005195140838623047 s elapsed
0] data.custom_dataloader) How many batches 6
Loading: no checkpoint found in ./github_ignore_material/saves/
Training mode still in the same stage: no_additional_info
0] data.custom_dataloader) batch 1 / 6 batch_size: 2 epoch: 0 avg_src_seq_len: 144 avg_trg_seq_len: 7
[GPU:0] 8.333 % it: 2 lr: 0.0001 n.acc: 1 avg loss: 2.995 elapsed: 0 m 1 s sec/iter: 0.6
0] data.custom_dataloader) batch 3 / 6 batch_size: 2 epoch: 0 avg_src_seq_len: 144 avg_trg_seq_len: 7
[GPU:0] 16.667 % it: 4 lr: 0.0002 n.acc: 1 avg loss: 2.688 elapsed: 0 m 1 s sec/iter: 0.047
0] data.custom_dataloader) batch 5 / 6 batch_size: 2 epoch: 0 avg_src_seq_len: 144 avg_trg_seq_len: 7
[GPU:0] 25.0 % it: 6 lr: 0.0002 n.acc: 1 avg loss: 3.057 elapsed: 0 m 1 s sec/iter: 0.075
Validation Loss on 3 samples: 2.6680939084007624
Evaluation on Validation Set
defaultdict(<class 'float'>, {('of', 'green', 'socks'): 1.0, ('green',): 1.0, ('of', 'green'): 1.0, ('a', 'pair', 'of'): 3.0, ('a', 'pair'): 3.0, ('of',): 3.0, ('pair', 'of'): 3.0, ('green', 'socks'): 1.0, ('pair', 'of', 'green'): 1.0, ('a', 'pair', 'of', 'green'): 1.0, ('pair', 'of', 'green', 'socks'): 1.0, ('pair',): 3.0, ('a',): 3.0, ('socks',): 3.0, ('pair', 'of', 'blue', 'socks'): 1.0, ('blue', 'socks'): 1.0, ('blue',): 1.0, ('of', 'blue'): 1.0, ('of', 'blue', 'socks'): 1.0, ('a', 'pair', 'of', 'blue'): 1.0, ('pair', 'of', 'blue'): 1.0, ('red', 'socks'): 1.0, ('of', 'red', 'socks'): 1.0, ('red',): 1.0, ('of', 'red'): 1.0, ('pair', 'of', 'red', 'socks'): 1.0, ('pair', 'of', 'red'): 1.0, ('a', 'pair', 'of', 'red'): 1.0})
Evaluation Phase over 3 BeamSize: 3  elapsed: 4 m 58 s
[('CIDEr', 0.0007), ('Bleu_1', 0.04), ('Bleu_2', 0.0236), ('Bleu_3', 0.0), ('Bleu_4', 0.0), ('ROUGE_L', 0.0758), ('SPICE', 0.0), ('METEOR', 0.0511)]
Saved to checkpoint_2023-08-27-14:30:59_epoch0it6bs2_xe_.pth
0] data.custom_dataloader) batch 1 / 6 batch_size: 2 epoch: 1 avg_src_seq_len: 144 avg_trg_seq_len: 7
[GPU:0] 33.333 % it: 8 lr: 0.0002 n.acc: 1 avg loss: 2.957 elapsed: 5 m 0 s sec/iter: 0.168
0] data.custom_dataloader) batch 3 / 6 batch_size: 2 epoch: 1 avg_src_seq_len: 144 avg_trg_seq_len: 7
[GPU:0] 41.667 % it: 10 lr: 0.0002 n.acc: 1 avg loss: 2.966 elapsed: 5 m 0 s sec/iter: 0.069
0] data.custom_dataloader) batch 5 / 6 batch_size: 2 epoch: 1 avg_src_seq_len: 144 avg_trg_seq_len: 7
[GPU:0] 50.0 % it: 12 lr: 0.00016 n.acc: 1 avg loss: 2.444 elapsed: 5 m 1 s sec/iter: 0.13
Validation Loss on 3 samples: 2.1883841015043712
Evaluation on Validation Set
defaultdict(<class 'float'>, {('of', 'green', 'socks'): 1.0, ('green',): 1.0, ('of', 'green'): 1.0, ('a', 'pair', 'of'): 3.0, ('a', 'pair'): 3.0, ('of',): 3.0, ('pair', 'of'): 3.0, ('green', 'socks'): 1.0, ('pair', 'of', 'green'): 1.0, ('a', 'pair', 'of', 'green'): 1.0, ('pair', 'of', 'green', 'socks'): 1.0, ('pair',): 3.0, ('a',): 3.0, ('socks',): 3.0, ('pair', 'of', 'blue', 'socks'): 1.0, ('blue', 'socks'): 1.0, ('blue',): 1.0, ('of', 'blue'): 1.0, ('of', 'blue', 'socks'): 1.0, ('a', 'pair', 'of', 'blue'): 1.0, ('pair', 'of', 'blue'): 1.0, ('red', 'socks'): 1.0, ('of', 'red', 'socks'): 1.0, ('red',): 1.0, ('of', 'red'): 1.0, ('pair', 'of', 'red', 'socks'): 1.0, ('pair', 'of', 'red'): 1.0, ('a', 'pair', 'of', 'red'): 1.0})
Evaluation Phase over 3 BeamSize: 3  elapsed: 0 m 15 s
[('CIDEr', 0.0021), ('Bleu_1', 0.0563), ('Bleu_2', 0.0288), ('Bleu_3', 0.0), ('Bleu_4', 0.0), ('ROUGE_L', 0.1046), ('SPICE', 0.0606), ('METEOR', 0.0749)]
Saved to checkpoint_2023-08-27-14:31:15_epoch1it6bs2_xe_.pth
0] data.custom_dataloader) batch 1 / 6 batch_size: 2 epoch: 2 avg_src_seq_len: 144 avg_trg_seq_len: 7
[GPU:0] 58.333 % it: 14 lr: 0.00016 n.acc: 1 avg loss: 2.312 elapsed: 5 m 17 s sec/iter: 0.056
0] data.custom_dataloader) batch 3 / 6 batch_size: 2 epoch: 2 avg_src_seq_len: 144 avg_trg_seq_len: 7
[GPU:0] 66.667 % it: 16 lr: 0.00016 n.acc: 1 avg loss: 2.582 elapsed: 5 m 17 s sec/iter: 0.056
0] data.custom_dataloader) batch 5 / 6 batch_size: 2 epoch: 2 avg_src_seq_len: 144 avg_trg_seq_len: 7
[GPU:0] 75.0 % it: 18 lr: 0.00016 n.acc: 1 avg loss: 2.246 elapsed: 5 m 17 s sec/iter: 0.058
Validation Loss on 3 samples: 1.880339122953869
Evaluation on Validation Set
defaultdict(<class 'float'>, {('of', 'green', 'socks'): 1.0, ('green',): 1.0, ('of', 'green'): 1.0, ('a', 'pair', 'of'): 3.0, ('a', 'pair'): 3.0, ('of',): 3.0, ('pair', 'of'): 3.0, ('green', 'socks'): 1.0, ('pair', 'of', 'green'): 1.0, ('a', 'pair', 'of', 'green'): 1.0, ('pair', 'of', 'green', 'socks'): 1.0, ('pair',): 3.0, ('a',): 3.0, ('socks',): 3.0, ('pair', 'of', 'blue', 'socks'): 1.0, ('blue', 'socks'): 1.0, ('blue',): 1.0, ('of', 'blue'): 1.0, ('of', 'blue', 'socks'): 1.0, ('a', 'pair', 'of', 'blue'): 1.0, ('pair', 'of', 'blue'): 1.0, ('red', 'socks'): 1.0, ('of', 'red', 'socks'): 1.0, ('red',): 1.0, ('of', 'red'): 1.0, ('pair', 'of', 'red', 'socks'): 1.0, ('pair', 'of', 'red'): 1.0, ('a', 'pair', 'of', 'red'): 1.0})
Evaluation Phase over 3 BeamSize: 3  elapsed: 0 m 14 s
[('CIDEr', 0.0005), ('Bleu_1', 0.12), ('Bleu_2', 0.0707), ('Bleu_3', 0.0), ('Bleu_4', 0.0), ('ROUGE_L', 0.0758), ('SPICE', 0.0513), ('METEOR', 0.1007)]
Saved to checkpoint_2023-08-27-14:31:30_epoch2it6bs2_xe_.pth
0] data.custom_dataloader) batch 1 / 6 batch_size: 2 epoch: 3 avg_src_seq_len: 144 avg_trg_seq_len: 7
[GPU:0] 83.333 % it: 20 lr: 0.00016 n.acc: 1 avg loss: 2.099 elapsed: 5 m 31 s sec/iter: 0.058
0] data.custom_dataloader) batch 3 / 6 batch_size: 2 epoch: 3 avg_src_seq_len: 144 avg_trg_seq_len: 7
[GPU:0] 91.667 % it: 22 lr: 0.00016 n.acc: 1 avg loss: 2.142 elapsed: 5 m 31 s sec/iter: 0.058
0] data.custom_dataloader) batch 5 / 6 batch_size: 2 epoch: 3 avg_src_seq_len: 144 avg_trg_seq_len: 7
[GPU:0] 100.0 % it: 24 lr: 0.000128 n.acc: 1 avg loss: 2.072 elapsed: 5 m 31 s sec/iter: 0.061
Validation Loss on 3 samples: 1.6649387904575892
Evaluation on Validation Set
defaultdict(<class 'float'>, {('of', 'green', 'socks'): 1.0, ('green',): 1.0, ('of', 'green'): 1.0, ('a', 'pair', 'of'): 3.0, ('a', 'pair'): 3.0, ('of',): 3.0, ('pair', 'of'): 3.0, ('green', 'socks'): 1.0, ('pair', 'of', 'green'): 1.0, ('a', 'pair', 'of', 'green'): 1.0, ('pair', 'of', 'green', 'socks'): 1.0, ('pair',): 3.0, ('a',): 3.0, ('socks',): 3.0, ('pair', 'of', 'blue', 'socks'): 1.0, ('blue', 'socks'): 1.0, ('blue',): 1.0, ('of', 'blue'): 1.0, ('of', 'blue', 'socks'): 1.0, ('a', 'pair', 'of', 'blue'): 1.0, ('pair', 'of', 'blue'): 1.0, ('red', 'socks'): 1.0, ('of', 'red', 'socks'): 1.0, ('red',): 1.0, ('of', 'red'): 1.0, ('pair', 'of', 'red', 'socks'): 1.0, ('pair', 'of', 'red'): 1.0, ('a', 'pair', 'of', 'red'): 1.0})
Evaluation Phase over 3 BeamSize: 3  elapsed: 0 m 13 s
[('CIDEr', 0.0), ('Bleu_1', 0.08), ('Bleu_2', 0.0), ('Bleu_3', 0.0), ('Bleu_4', 0.0), ('ROUGE_L', 0.0505), ('SPICE', 0.0), ('METEOR', 0.0489)]
Saved to checkpoint_2023-08-27-14:31:44_epoch3it6bs2_xe_.pth
[GPU: 0 ] Closing...


  </details>
  
and this is the command

```
python3.7 train.py --N_enc 3 --N_dec 3  \
    --model_dim 32 --seed 775533 --optim_type radam --sched_type custom_warmup_anneal  \
    --warmup 4 --lr 2e-4 --anneal_coeff 0.8 --anneal_every_epoch 2 --enc_drop 0.1 \
    --dec_drop 0.1 --enc_input_drop 0.1 --dec_input_drop 0.1 --drop_other 0.1 \
    --batch_size 2 --num_accum 1 --num_gpus 1 --ddp_sync_port 11317 --eval_beam_sizes [3]  \
    --save_path ./github_ignore_material/saves/ --save_every_minutes 60 --how_many_checkpoints 1  \
    --is_end_to_end False --features_path <MY_PATH_TO_TOY_FEATURES>/features.hdf5 --partial_load False \
    --captions_path <MY_PATH_TO_TOY_JSON> \
    --print_every_iter 2 --eval_every_iter 999999 \
    --reinforce False --num_epochs 4
```

I hope the files in the drive can provide some insight into the problem... for instance, performing [git] diff between our codes can be helpful, in addition to comparing the outputs in case you feed the toy files into your code (I'm omitting the data generation step, more details regarding this step can be found here https://github.com/jchenghu/ExpansionNet_v2/issues/5)

 Let me know if it helped!

**Comment by myyzzzoooo** [comment]
Hi,
Fortunately, I solved the problem. 
It was a problem with SPICE.jar, and we decided not to calculate the spice value for now... :) 
Thank you for your concern!

And can I ask one more question please?
During third stage(Cross-Entropy Training: End to End Training), I got OOM at compute_evaluation_loss function in test.py
Is there any method to avoid this problem? (I already reduce the batch size to 1 but it doesn't work)
Thank you so much!!

**Comment by jchenghu** [comment]
> Hi, Fortunately, I solved the problem. It was a problem with SPICE.jar, and we decided not to calculate the spice value for now... :) Thank you for your concern!
> 

That's great! I'm glad you solved the issue for now. Feel free to open another discussion (or continue here) in the future if you need help :-) (It would surely also help me as well since I'm currently not aware of bug or compatibility problems related to SPICE.jar)

> And can I ask one more question please? During third stage(Cross-Entropy Training: End to End Training), I got OOM at compute_evaluation_loss function in test.py Is there any method to avoid this problem? (I already reduce the batch size to 1 but it doesn't work) Thank you so much!!

before diving into more complex solutions, may I ask if you tried reducing the '--eval_parallel_batch_size' argument

**Comment by myyzzzoooo** [comment]
OMG I'm sorry, I should have checked the arguments first...
Now, everything works fine. 
Thank you again for everything you’ve done!

**Comment by jchenghu** [comment]
Actually, I think my poor / lack of documentation is at fault here... 

You're welcome! I'm glad I helped.
